import { Lato } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import TopBar from "@/components/TopBar";

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'], 
  variable: '--font-lato', 
  display: 'swap', 
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <html lang="en" className={`${lato.className} h-full`}>
      <body className="h-full">
        <div className="flex h-full overflow-hidden">
          <Sidebar />
          <div className="flex-1">
            <TopBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}